### ISSUE TITLE
Cannot read properties of null (reading '_env')

### ISSUE THREAD

**Issue by gnasnik** [authorizerdev/authorizer#140]
get an error `Cannot read properties of null (reading '_env')` when I use IP and port( http://192.168.1.100:8080)  to login dashboard, and I refresh the page need login again,  but I didn't have this problem with localhost+port (http://localhost:8080).

**Comment by lakhansamani** [comment]
@gnasnik thanks for reporting, will look into this shortly

**Comment by lakhansamani** [comment]
![Screenshot 2022-03-17 at 1 35 37 PM](https://user-images.githubusercontent.com/6964334/158764402-5b3eb56f-03d9-41d9-b5d2-a6018ab83007.png)

@gnasnik browser will not allow setting http only cookie for non https urls other than `localhost` and `127.0.0.1`

I would recommend using a correct domain and valid SSL certificate in this case.
