### ISSUE TITLE
Add validation to set strong password

### ISSUE THREAD

**Issue by lakhansamani** [authorizerdev/authorizer#141]
**Feature Description**
 During signup & reset password it should validate to set strong password.
Strong password should be of
- Min 6 chars
- Max 36 chars
- Should have atleast 1 special char
- Should have atleast 1 capital letter
- Should have atleast 1 number
- Should have atleast 1 small letter

**Describe the solution you'd like**

- Add util which checks for above mentioned password validation during signup + reset password
- Add similar validation in authorizer-react
- Update authorizer-react version for /app

**Describe alternatives you've considered**

**Additional context**

**Comment by hmmhmmhm** [comment]
@lakhansamani 
This is powerful, but it is difficult to use in services that require simple membership due to too strong a password rule. Is it possible to release this as an option?

**Comment by lakhansamani** [comment]
@hmmhmmhm van you describe membership use case in more detail?

**Comment by hmmhmmhm** [comment]
@lakhansamani It having this problem when I'm developing game services for students. They feel that it's excessive just to include special characters and numbers, and they're complaining about putting capital letters.

**Comment by lakhansamani** [comment]
Let me see what I can do about it. Probably will try to add a setting to disable strong password check

**Comment by lakhansamani** [comment]
@hmmhmmhm is it okay to have min 6 char validation?

**Comment by hmmhmmhm** [comment]
@lakhansamani Yeah, I think that should be default check

**Comment by lakhansamani** [comment]
@hmmhmmhm I have added this feature as part of the 0.33.0 release.
You can update your instance and disable a strong password from the dashboard.
Also please consider upgrading FE libraries if you are using them.

<img width="1679" alt="Screenshot 2022-06-18 at 3 33 42 PM" src="https://user-images.githubusercontent.com/6964334/174432942-7c9aad35-ac79-4761-b822-6d9acbdcfd04.png">

**Comment by hmmhmmhm** [comment]
@lakhansamani thx so much!!!
