### ISSUE TITLE
Can't send password reset code.

### ISSUE THREAD

**Issue by peter-wd-1** [authorizerdev/authorizer#175]
**Version:** x.y.z
[0.22.0](https://github.com/authorizerdev/authorizer/releases/tag/0.22.0)

**Describe the bug**
If I use forgot password link in authorizor component of react, server i get 
```
[Oauth_authserver.--    | [GIN] 2022/05/29 - 01:08:12 | 204 |        25.3µs |   172.58.239.52 | OPTIONS  "/graphql"
auth_authserver.--   | [GIN] 2022/05/29 - 01:08:12 | 200 |    4.989414ms |   172.58.239.52 | POST     "/graphql"
```
But email is not sent. 
I'm using next docker compose file. Server deployed on ec2 instance and has own domin like https://admin.domain.com
```
   environment:
     ....
      - AUTHORIZER_URL=https://www.admin.rfiready.co
      - RESET_PASSWORD_URL=https://www.rfiready.co/resetpassword
      - DISABLE_MAGIC_LINK_LOGIN=true
      ....
```
I also turned off verification email env. 
It all works fine on localhost

**Steps To Reproduce**
1. deploy on ssl domain connected on ec2 instance.
2. set `RESET_PASWORD_URL`
3. use React Authorizer component.
4. use forgot password link

**Expected behavior**

should be able

**Screenshots**

**Desktop (please complete the following information):**

- OS: ubuntu
- Browser chrome
- Version latest

**Additional context**

**Comment by lakhansamani** [comment]
@peter-wd-1 have you configured SMTP env variables?

**Comment by peter-wd-1** [comment]
I have sendgrid used for this

**Comment by lakhansamani** [comment]
There should be failure log with 0.23.0
That would allow us to debug further

Make sure you use --log_level=debug as command line arg while starting the server

**Comment by peter-wd-1** [comment]
Yh, I found the resent update is very tempting. I have changed the code and it'd be hard to upgrade the version. Currently I've just clone the repo into our repo. But would you have any recommendation for having customized code within authorizer. And make it flexible to upgrade? Should I fork it and maintain own branch?

**Comment by lakhansamani** [comment]
Would like to know what are the customizations that need.

Also the upcoming releasing on making authorizer service highly available has some more interesting changes.

**Comment by peter-wd-1** [comment]
I've update the latest one 0.23.0 and still cannot send a mail. 
Now I'm using gmail smtp. 
Credential is correct but getting this error from the log.

```
{"file":"/authorizer/server/email/verification_email.go:110","func":"github.com/authorizerdev/authorizer/server/email.SendVerificationMail","level":"warning","msg":"error sending email: 535 5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials p6-20020a05620a056600b0069fc13ce23bsm3312698qkp.108 - gsmtp","time":"2022-06-02T17:30:42Z"}
```

**Comment by lakhansamani** [comment]
Seems a permission issue. In google u have to make it insecure to make it work till I remember.

**Comment by lakhansamani** [comment]
Did you try with sendgrid?

**Comment by peter-wd-1** [comment]
Yup sendgrid, Actually no problem sending it from own api but I think it's somehow blocked. Guess it got detected as a spam. So I created new account on gmail.

**Comment by peter-wd-1** [comment]
Enabled Gmail setting but no luck :(
![Screen Shot 2022-06-02 at 1 48 38 PM](https://user-images.githubusercontent.com/65737603/171694438-64633549-1a7d-4146-8db0-c9a91ae083e9.png)

**Comment by lakhansamani** [comment]
Okay. I did try it in past in few days you will see gmail will again stop sending emails so not a reliable solution.

You can try different SENDER_EMAIL for sendgrid.

**Comment by lakhansamani** [comment]
@peter-wd-1 closing this issue as it is more of mailing service issue.
