### ISSUE TITLE
Add Custom OAuth

### ISSUE THREAD

**Issue by hmmhmmhm** [authorizerdev/authorizer#176]
**Feature Description**

 it would be nice to add other providers that follow the standard OAuth protocol.

**Describe the solution you'd like**

Once the OAuth URL is entered, a dashboard function is required to send requests according to the default behavior.

**Comment by lakhansamani** [comment]
@hmmhmmhm there would be problems if their data returned is in different structure.
For example if you check here had to process user info for all users in different way: https://github.com/authorizerdev/authorizer/blob/main/server/handlers/oauth_callback.go#L204

**Comment by lakhansamani** [comment]
Though adding more providers is in pipeline: it should be fairly simple as we have to introduce changes minimal places.
We are currently using for oauth2: https://github.com/golang/oauth2

**Comment by hmmhmmhm** [comment]
well... if user parsing has make problem, what if just verify the user email information and don't use the rest of the user information? Isn't the method of requesting data under the oauth 2.0 protocol the same and the exception processing is slightly different? this may be useful if you allow only very limited validation in custom pipeline.

**Comment by lakhansamani** [comment]
Yeah! Let me see what I can do about this. Putting this request in pipeline

**Comment by peter-wd-1** [comment]
I've also thought this would be great to have. thanks to bring this up @hmmhmmhm

**Comment by lakhansamani** [comment]
Closing this for now, as its better to support individual oauth2s each of them have their own complexities
