### ISSUE TITLE
Support for ScyllaDB

### ISSUE THREAD

**Issue by PeterCorless** [authorizerdev/authorizer#177]
**Support for ScyllaDB**

Read about Authorizer support for Cassandra [#126](https://github.com/authorizerdev/authorizer/issues/126#issue-1137259428) .

 Which should make it also compatible with [ScyllaDB Open Source](https://www.scylladb.com/download/#open-source).

**Validate Compatibility; Add to README**

Would love it if you could validate Authorizer works with ScyllaDB Open Source, and we can recommend it as a solution to our user base.

**Alternatives**

ScyllaDB also has commercial Enterprise and DBaaS offerings; we'd presume those would also work once testing was complete on open source.

**Comment by lakhansamani** [comment]
@PeterCorless thank you for the great suggestion will perform testing and let you know the results

**Comment by lakhansamani** [comment]
@PeterCorless all the integration tests are passing for Scylla DB and also did the basic manual testing :-)
I have tested with the OSS docker version

```
version: '3.9'

services:
  db:
    container_name: scylla
    image: scylladb/scylla
    ports:
      - 9042:9042
```

Is there any specific things that I should be aware for the cloud version?

**Comment by lakhansamani** [comment]
@PeterCorless getting some error with cloud version

I followed instructions given on `connect` section

```

package main

import (
    "fmt"
    "github.com/gocql/gocql"
)

func main() {
    var cluster = gocql.NewCluster("52.73.35.105", "34.206.99.120", "34.195.225.4")
    cluster.Authenticator = gocql.PasswordAuthenticator{Username: "scylla", Password: "***************"}
    cluster.PoolConfig.HostSelectionPolicy = gocql.DCAwareRoundRobinPolicy("AWS_US_EAST_1")

    var session, err = cluster.CreateSession()
    if err != nil {
        panic("Failed to connect to cluster")
    }
}
    
```

<img width="1438" alt="Screenshot 2022-06-05 at 11 33 42 AM" src="https://user-images.githubusercontent.com/6964334/172037641-17d05f18-f87c-43ac-bc2d-b050287a7d9d.png">

**Comment by avikivity** [comment]
It should work exactly the same. It look like you don't have connectivity to the cluster IP addresses.

**Comment by lakhansamani** [comment]
@avikivity i tried with default ip detection that scylladb dashboard does.

Though will try it again and let you know

**Comment by lakhansamani** [comment]
@avikivity I tried one more time, still getting the same error.
I also verified my IP address it is whitelisted correctly.

**Comment by avikivity** [comment]
I can't help on this bug tracker, it's a connectivity problem that happens before you ever reach Scylla. Try the #cloud channel in https://slack.scylladb.com.

**Comment by lakhansamani** [comment]
@PeterCorless I have added support for ScyllaDB, it would be great if you can spread the word in the community thanks.
