### ISSUE TITLE
sendgrid - You are not authorized to access SendGrid, please contact Support.

### ISSUE THREAD

**Issue by shuvo3** [authorizerdev/authorizer#179]
I have created a new account and tried to log in, but getting an issue _**You are not authorized to access SendGrid, please contact [Support](https://support.sendgrid.com/)**_. The worst thing is I can't get support without a login.

**Comment by lakhansamani** [comment]
@shuvo3 it is SendGrid error and not authorizer.

Closing this issue for now. Let us know if you face issue with sendgrid integration on authorizer
