### ISSUE TITLE
[dashboard] user deletion does not refresh the list on dashboard

### ISSUE THREAD

**Issue by lakhansamani** [authorizerdev/authorizer#186]
**Version:** 0.28.0

**Describe the bug**
After the admin deletes a user still it appears on list. After refresh its gone.

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by anik-ghosh-au7** [comment]
@lakhansamani I couldn't replicate this issue

https://user-images.githubusercontent.com/59804102/173175900-9fa02b60-e6e5-47f0-baa8-54cfe8e2dc24.mp4

**Comment by lakhansamani** [comment]
Closing for now as not reproducible
