### ISSUE TITLE
Can't open dashboard page on windows using authorizer-0.38.0-windows-amd64

### ISSUE THREAD

**Issue by wubin1989** [authorizerdev/authorizer#203]
![image](https://user-images.githubusercontent.com/12456315/179972650-7c28f98c-1c49-4288-a298-cfb6f1b4294b.png)

**Comment by lakhansamani** [comment]
@wubin1989 I think dashboard and app build is missing

Please check contributing guide here: https://github.com/authorizerdev/authorizer/blob/main/.github/CONTRIBUTING.md#L43

I will update readme.md with this

Let me know if it works after that

**Comment by lakhansamani** [comment]
@wubin1989 closing this for now,
Feel free to re-open if issue continues
