### ISSUE TITLE
Feature: Support Discord Authorization

### ISSUE THREAD

**Issue by foestauf** [authorizerdev/authorizer#214]
**Feature Description**

Add support to allow login via Discord OAuth2 flow.
https://discord.com/developers/docs/topics/oauth2

**Describe the solution you'd like**

Utilize Discord as an identify provider.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by lakhansamani** [comment]
Thank you @foestauf for adding, soon will be adding support for this 👍
