### ISSUE TITLE
Allow empty SMTP_USERNAME and SMTP_PASSWORD

### ISSUE THREAD

**Issue by ruessej** [authorizerdev/authorizer#223]
**Feature Description**

Some SMTP don't use any authentication.
And maybe update to a more maintained mail pkg (like https://github.com/xhit/go-simple-mail).

**Comment by lakhansamani** [comment]
Thanks @ruessej for sharing it
Can you share SMTP providers that don't use auth, because I feel then it would be a security concern in some sense ;-)

**Comment by lakhansamani** [comment]
Ah, I see!
In that case, passing any random values to SMTP USERNAME & PASSWORD should do the job right ;-) 

Just want to keep those with security concerns
