### ISSUE TITLE
[Security] Login endpoint response bring to much details about the credentials

### ISSUE THREAD

**Issue by brunocascio** [authorizerdev/authorizer#224]
**Version:** 1.1.0

**Describe the bug**

The API says if the email or password is invalid instead of a generic message like "Email **or** password are invalid"
So an attacker would know if the email exists or not in a database and then brute force existing emails only.

**Steps To Reproduce**

Scenario with existing email + invalid password:

```
mutation {
  login(params:{email:"existing@email.com", password:"invalidOne"}) {
    access_token
  }
}
```

API response:

```json
{
  "errors": [
    {
      "message": "invalid password",
      "path": [
        "login"
      ]
    }
  ],
  "data": null
}
```

Scenario with non-existing email + whatever password:

```
mutation {
  login(params:{email:"nonexisting@email.com", password:"whateverHere"}) {
    access_token
  }
}
```

```json
{
  "errors": [
    {
      "message": "user with this email not found",
      "path": [
        "login"
      ]
    }
  ],
  "data": null
}
```

**Expected behavior**

The API should respond always with a generic message instead of specifying the technical issue.
Example:

```json
{
  "errors": [
    {
      "message": "Bad user credentials",
      "path": [
        "login"
      ]
    }
  ],
  "data": null
}
```

**Comment by lakhansamani** [comment]
Thanks @brunocascio for this important feedback. Will adjust the msg in upcoming release

**Comment by knpwrs** [comment]
I was going to say the same thing except from a privacy perspective rather than strictly security. Right now the password recovery screen can have an error like "User with this email not found." It would be better if the same message was shown on success or error and it said something like, "if a user with this email address is found a password reset link will be sent."
