### ISSUE TITLE
Verification requests are not removed if a user is deleted

### ISSUE THREAD

**Issue by jerebtw** [authorizerdev/authorizer#234]
**Version:** 1.1.5

**Describe the bug**

When you delete a user verification request are not delete

**Steps To Reproduce**

Delete a user with a open verification request

**Expected behavior**

Delete it

**Screenshots**

![image](https://user-images.githubusercontent.com/49494752/190497184-abd5d9ac-b1d7-4b4d-a6ec-d4591a083ab4.png)

![image](https://user-images.githubusercontent.com/49494752/190497210-a7d36b56-3b34-4608-aa4b-a378cb1e2038.png)

**Comment by lakhansamani** [comment]
Thank you for reporting it will fix it soon.
Though not a blocker I suppose.

**Comment by jerebtw** [comment]
No, I just wanted to report it ;)

**Comment by ruessej** [comment]
When you remove a user and try to add a new user it also makes a internal error

**Comment by lakhansamani** [comment]
@ruessej thank you for reporting a new use case around it.
I will fix it asap

**Comment by lakhansamani** [comment]
@ruessej @jerebtw released as part of 1.1.6
