### ISSUE TITLE
Admin SDK

### ISSUE THREAD

**Issue by jerebtw** [authorizerdev/authorizer#237]
**Feature Description**

Add a admin SDK for go or node (or i'm blind)

**Comment by lakhansamani** [comment]
@jerebtw there is no admin sdk but you can always access all the admin features via Dashboard or its APIs

Check docs for api: https://docs.authorizer.dev/core/graphql-api

All the apis starting with underscore (_) are admin apis

**Comment by jerebtw** [comment]
Okay thanks, I didn't saw that
