### ISSUE TITLE
Log internal server errors

### ISSUE THREAD

**Issue by ruessej** [authorizerdev/authorizer#240]
**Feature Description**

If any thing errors internal the logs should contain the error that you can debug/report the problem

**Comment by lakhansamani** [comment]
@ruessej did you try with `log_level` error?

**Comment by ruessej** [comment]
Thanks didn't saw that

**Comment by jerebtw** [comment]
> @ruessej did you try with `log_level` error?
> 
> https://docs.authorizer.dev/core/cli

Is there a way to set it via the envs?

**Comment by lakhansamani** [comment]
We don't have it,
I will add it soon
