### ISSUE TITLE
Error on startup (EnvKeyAppCookieSecure)

### ISSUE THREAD

**Issue by ruessej** [authorizerdev/authorizer#241]
It just random got this error (I started Authorizer many times before with no issue):

panic: interface conversion: interface {} is string, not bool

goroutine 1 [running]:
github.com/authorizerdev/authorizer/server/env.InitAllEnv()
        /authorizer/server/env/env.go:434 +0x8885
main.main()
        /authorizer/server/main.go:92 +0x5b6

https://github.com/authorizerdev/authorizer/blob/221009bf0a9210c93db910111674116dafe18d0c/server/env/env.go#L422

Also i would suggest to split this file in more function because currently its quit a lot to see

**Comment by ruessej** [comment]
Looks like the database save or something doesn't work

**Comment by lakhansamani** [comment]
@ruessej thank you for reporting it,
Quick solution could be reset this variable via `.env` variable.

I will take deeper look into this today
Thank you

**Comment by lakhansamani** [comment]
@ruessej also can you pls share which DB and version you are using?

**Comment by lakhansamani** [comment]
Next major version will have a breaking change where we will be putting all env vars under single source of truth and then this file size will be reduced.

**Comment by ruessej** [comment]
I use mssql.

When i delete the env table data the problem doesn't exist (Only after some restartes it begins again)

**Comment by lakhansamani** [comment]
@ruessej released as part of 1.1.6

**Comment by ruessej** [comment]
Thanks, I did not see the other places where I should insert these constants
