### ISSUE TITLE
CORS from localhost

### ISSUE THREAD

**Issue by VladimirCores** [authorizerdev/authorizer#250]
Wanna finish my experiment. But face the CORS problem. Docker runs on 8081, and client on `http://localhost:5173/`, whitlisted: 

![image](https://user-images.githubusercontent.com/442111/192870957-27ab4c12-e94a-49ec-910e-d347bc9da481.png)
(BTW: it (the list) is not restored after container restarted) 

And still have a CORS error:

![Screenshot_select-area_20220928221055](https://user-images.githubusercontent.com/442111/192871168-a967a755-ed20-4cd3-895b-068bc666ccee.png)

Appreciate any suggestion?

**Comment by lakhansamani** [comment]
@VladimirCores I am not able to reproduce,
Here are the steps I followed

https://www.loom.com/share/ec260f1d0fd241ce8aec85c015ca2e76

**Comment by lakhansamani** [comment]
@VladimirCores let me know if this good to close!

**Comment by VladimirCores** [comment]
@lakhansamani here is an example project, I'm requesting profile after login `.authorize({})`.
[welcome-authorizer-vite-vanilla.zip](https://github.com/authorizerdev/authorizer/files/9717998/welcome-authorizer-vite-vanilla.zip)

**Comment by VladimirCores** [comment]
@lakhansamani why closed? You can't reproduce?

**Comment by lakhansamani** [comment]
@VladimirCores sorry closed by mistake was about to re-open it.

Though I tried reproducing it, the extra headers you are sending is creating problems
Remove that from the code and it should work.

```
 'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': '*',
    'Access-Control-Allow-Methods': 'POST, GET, OPTIONS, DELETE',
    'Access-Control-Allow-Credentials': 'true',
```

**Comment by lakhansamani** [comment]
Let me know if you face issue after remove the headers you are setting.

**Comment by lakhansamani** [comment]
Regarding CORS headers, they should always be set from backend and not frontend
We are doing it from: https://github.com/authorizerdev/authorizer/blob/main/server/middlewares/cors.go

**Comment by lakhansamani** [comment]
@VladimirCores here is small demo of it
https://www.loom.com/share/73bf3582920a43ada71cdb39e227e66f

**Comment by lakhansamani** [comment]
@VladimirCores here is the demo
https://www.loom.com/share/45576ae729384d259f0eca15099b24cc

**Comment by VladimirCores** [comment]
Cool, all works! Thank you @lakhansamani for great support! : ) 
Continue investigation of the tool...
