### ISSUE TITLE
Protected roles are only protected if they aren't defined as normal roles

### ISSUE THREAD

**Issue by knpwrs** [authorizerdev/authorizer#264]
**Version:** [e760a55](https://github.com/authorizerdev/authorizer/commit/e760a5598e5e7d3822bffb5fbb18cc494a21a546)

**Describe the bug**

Consider the documentation for environment variables:

<table>
<th>
<tr>
<td>Variable
<td>Description
<td>Default Value
</tr>
<tr>
	<td> <code>ROLES
	<td>Comma separated list of roles that your platform supports
	<td> <code>user,admin</code>
<tr>
	<td> <code>PROTECTED_ROLES
	<td>Comma separated list of roles for which signup should be disabled. Example admin roles. This roles can only assigned manually via super admin like <code>adminUpdateProfile</code>.
	<td>
</table>

This seems to imply that one should define `admin` in both `ROLES` _and_ `PROTECTED_ROLES`; however, if one does this, then anyone is able to sign up with the `admin` role.

**Steps To Reproduce**

1. Spin up the app and define `admin` and `user` as roles, and `admin` as a protected role.
2. Go to the API playground.
3. Observe that you can sign up using the `admin` role
4. Go back to Authorizer and remove the `admin` role, but leave it as a `protected` role
5. Go back to the API playground and observe that you can no longer sign up using the admin role.

**Expected behavior**

Depends. This could either be a documentation issue or an actual bug.

**Comment by lakhansamani** [comment]
@knpwrs there is some miss understanding here u should not put protected roles like admin in the roles input box.

**Comment by lakhansamani** [comment]
Closing this for now. Let us know if you still face the same issue
