### ISSUE TITLE
Available to set SMTP Local name

### ISSUE THREAD

**Issue by mzch** [authorizerdev/authorizer#274]
**Feature Description**

Please add SMTP Local Name, e.g. `SMTP_LOCALNAME`, to `.env`, because `mail.v2` package sends `EHLO` command with `localhost` in default configuration but some mail hosts reject such a  connection. See below:
```
Oct 12 14:05:00 db server[957190]: {"level":"debug","msg":"SMTP Failed: gomail: could not send email 1: 450 4.7.1 \u003clocalhost\u003e: Helo command rejected: Host not found","time":"2022-10-12T21:05:00Z"}
```
**Describe the solution you'd like**

Set `Dialer.LocalName` before `DialAndSend` func. Refer https://pkg.go.dev/gopkg.in/gomail.v2?utm_source=godoc#Dialer

**Describe alternatives you've considered**

None.

**Additional context**

**Comment by lakhansamani** [comment]
@mzch thank you for putting it up.
I will add it in upcoming release

**Comment by lakhansamani** [comment]
@mzch I have added support for `Dialer.LocalName` in 1.1.22
