### ISSUE TITLE
forgotPassword link and redirect

### ISSUE THREAD

**Issue by ruessej** [authorizerdev/authorizer#275]
**Version:** 1.1.21.beta.0

**Describe the bug**

When calling forgotPassword, the email does not contain a url, just "?token=...", but only the first time after starting the container (or when restarting the container).

I'm not sure, but shouldn't the email be redirected to the redirect_uri (if you want to have a custom password reset form) or should the password reset form redirect to the redirect_uri after the user changes the password?

**Comment by lakhansamani** [comment]
So the default redirect URL for forgot password is the APP url from where the request is made
https://github.com/authorizerdev/authorizer/blob/main/server/resolvers/forgot_password.go#L65

But lets say you don't have form, you can specifically mention the redirect_uri in the forgot_password request.
I see that it is not documented in [docs](https://docs.authorizer.dev/core/graphql-api#forgot_password) but it is part of graphql documentation


<img width="427" alt="Screenshot 2022-10-13 at 4 29 59 PM" src="https://user-images.githubusercontent.com/6964334/195610235-3ac167d2-41df-489c-8867-434abb198daa.png">

let me know if that doesn't work

**Comment by ruessej** [comment]
So if I specify another redirect_uri the url in the email should be the redirect_uri or?

**Comment by lakhansamani** [comment]
Token will have that information and it will redirect once the password is reset

**Comment by ruessej** [comment]
What i saw that didn't happend

**Comment by lakhansamani** [comment]
Okay I will debug and share my result.

**Comment by lakhansamani** [comment]
@ruessej if we return redirect uri with reset-password, I think frontend can redirect further, right?

**Comment by jerebtw** [comment]
What do you mean with reset-password?

**Comment by lakhansamani** [comment]
There is `reset_password` mutation, which you need to call after the forgot password. This mutation takes the token as input and a new password. This is what we call on the default app

https://docs.authorizer.dev/core/graphql-api#reset_password

**Comment by ruessej** [comment]
> @ruessej if we return redirect uri with reset-password, I think frontend can redirect further, right?

So that would redirect from email to the default app and then to the custom front end, or?

**Comment by lakhansamani** [comment]
@ruessej sorry for the late reply yes that is true

**Comment by jerebtw** [comment]
Okay, currently it does not redirect to my custom frontend

**Comment by lakhansamani** [comment]
Okay looking into this bug

**Comment by lakhansamani** [comment]
@ruessej I was able to reproduce it.
I have resolved this in 1.1.22

Test example: https://github.com/lakhansamani/authorizer-custom-forgot-password-test
Fixed here: Fixed: https://github.com/authorizerdev/authorizer/commit/e6900666527ebb6765fd85631697c1d9585fdb1b
