### ISSUE TITLE
Phone number is unique

### ISSUE THREAD

**Issue by jerebtw** [authorizerdev/authorizer#278]
**Version:** 1.1.21.beta.0

**Describe the bug**

2 users cannot log in if both have a null as phone number

**Expected behavior**

Phone number should accept anyone who does not have a number

**Comment by lakhansamani** [comment]
I have all the users with null phone numbers and it is working for me.
I suppose this is with SQLSERVER?

**Comment by jerebtw** [comment]
Yes, and it's annoying because I give each user a random phone number.

**Comment by lakhansamani** [comment]
Okay, I will test it more and share my result.
Though the problem is I am not able to test with SQLServer 2019 on my mac.

**Comment by lakhansamani** [comment]
@jerebtw I have fixed this in #279 
It will be part of 1.1.21 [Will be out in next 10 min- build in process]
