### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by jerebtw** [authorizerdev/authorizer#291]
**Version:** 1.1.27-beta.10

**Describe the bug**

fatal file=/authorizer/server/db/db.go:34 func=github.com/authorizerdev/authorizer/server/db.InitDB msg=Failed to initialize SQL driver: mssql: ALTER TABLE ALTER COLUMN phone_number failed because one or more objects access this column.

**Comment by lakhansamani** [comment]
This could be the side effect of updating sqlserver driver version
https://github.com/authorizerdev/authorizer/compare/1.1.26...1.1.27
