### ISSUE TITLE
BUG? Crash client apps

### ISSUE THREAD

**Issue by mzch** [authorizerdev/authorizer#304]
**Version:** 1.1.30

**Describe the bug**

Unable login to [Gitea](https://github.com/go-gitea/gitea) and [GItBucket](https://github.com/gitbucket/gitbucket). Gitea reports only `500` Error. Gitbucket reports `Missing JSON object member with key subject_types_supported`.

**NOTE**: Using [KeyCloak](https://github.com/keycloak/keycloak) or [Casdoor](https://github.com/casdoor/casdoor), Both Gitea and GItbucket allow to login successfully.

**Steps To Reproduce**

1. Set Authorizer as OpenID Provider in Gitea and GItBucket.
2. Login using Authorizer.

**Expected behavior**

Login successfully.

**Gitea and Authorizer Logs**
See [this Gist](https://gist.github.com/mzch/4578b4f7e017f0f89cabaa20a2c1b665).

**GitBucket Log**
See [this Gist](https://gist.github.com/mzch/4ff41f9743fff77976bc035fff754c6f).

**Server:**

- OS: Debian `11.5`

**Desktop (please complete the following information):**

- OS: macOS `13.0.1`
- Browser: Chrome
- Version `108.0.5359.98`

**Comment by lakhansamani** [comment]
@mzch thank you for reporting it
I will fix this in upcoming release

**Comment by lakhansamani** [comment]
@mzch I am trying to test this piece after making some fixes.
Can you share exact steps to configure open id settings on gitbucket and gitea

Thanks
