### ISSUE TITLE
[app] Fix responsiveness of universal login page

### ISSUE THREAD

**Issue by lakhansamani** [authorizerdev/authorizer#305]
**Version:** 1.1.31

**Describe the bug**

When /app is opened on custom browser in android and social media buttons are present, responsiveness is broken.

![Screenshot_20221220-121615](https://user-images.githubusercontent.com/6964334/208601795-35156e10-4c21-4329-9cf3-7b04012fb867.jpg)

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: android
- Browser: custom
- Device: 1plus 6t

**Additional context**

**Comment by MMahendra001ScaleTech** [comment]
I am working on this issue. Will create pr for this at weekend.

**Comment by lakhansamani** [comment]
Thanks @MMahendra001ScaleTech
