### ISSUE TITLE
bug:Facing problems when we provide a phone number in the signup.

### ISSUE THREAD

**Issue by minilikmila** [authorizerdev/authorizer#306]
**Version:**  Currently I'm using 1.1.28-rc.4 , but also I tried on latest Version

**Describe the bug**
When signing up with the phone number we get an error message like "user with given phone number already exists", but there is no 
such user with a given phone number.

**Steps To Reproduce**
1. Provide necessary credentials including phone_number to Authorizer sign up mutation.
2. Try to sign up.

**Expected behavior**

1.  We should sign up by providing phone_number as intended to do on it.
3. And we also should be able to log in with phone_number, like email. Basic log-in using phone_number and password. Because using phone numbers is necessary for some business logic and user types.

**Screenshots**
![Screenshot from 2022-12-20 16-44-08](https://user-images.githubusercontent.com/57789923/208683880-436175b9-3771-4314-87d8-1b8b0baec9d0.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser Firefox
- Version 22.04

**Additional context**

**Comment by lakhansamani** [comment]
@minilikmila thank you for reporting it
1. Can you upgrade to 1.1.30
2. Can you share details about the DB & its version you are using for this instance.

**Comment by minilikmila** [comment]
@lakhansamani 
Of course, I also tried 1.1.30 and faced the same error.
And I'm using PostgreSQL DB, and its Version is 15.1.

**Comment by lakhansamani** [comment]
@minilikmila thank you for sharing this
I will fix this in upcoming version

**Comment by lakhansamani** [comment]
@minilikmila it requires more to achieve mobile-based basic as the system is not designed in that way.
I am working on it: https://github.com/authorizerdev/authorizer/pull/307

In the next 1-2 days will have a beta release for all SQL based dbs.

**Comment by lakhansamani** [comment]
@minilikmila 
fix + mobile login & signup is getting released as 1.1.31 but I would say mobile signup is under beta as 
1. Needs a setup where users can configure TWILIO / similar applications to send SMS
2. Enable / Disable this feature from the dashboard
3. Implementing this feature as part of the SDKs & Libraries we have.
4. Implementing this feature as part of the universal login page.

Will be creating independent issues for the above enhancement and releasing them with upcoming releases.

**Comment by minilikmila** [comment]
@lakhansamani 
Good work, appreciated. may be I also need to participate on it.
