### ISSUE TITLE
how run the service through the go run command and specify the environment variables

### ISSUE THREAD

**Issue by dgodance** [authorizerdev/authorizer#312]
hello
how run the service through the go run command and specify the environment variables

**Comment by lakhansamani** [comment]
@dgodance checkout the project setup guide on readme.md
https://github.com/authorizerdev/authorizer#project-setup

**Comment by dgodance** [comment]
> @dgodance checkout the project setup guide on readme.md https://github.com/authorizerdev/authorizer#project-setup

How to access the server and the log after execution;

access  localhost:8080 then  HTTP ERROR 400

![image](https://user-images.githubusercontent.com/1674662/210039065-fdda3f93-bbaf-4a1d-bd4e-a7417f6a577e.png)

![image](https://user-images.githubusercontent.com/1674662/210039231-cb0f16e7-6404-43e1-b4c1-b35e0c6ace53.png)

**Comment by lakhansamani** [comment]
@dgodance you can start server in `log_leve=debug` mode to get more detailed logs
eg:

```
./build/server --env_file .env.local --log_level=debug
```
