### ISSUE TITLE
Access token expired

### ISSUE THREAD

**Issue by iamxvbaba** [authorizerdev/authorizer#316]
How to extend the expiration time of access token.

**Comment by lakhansamani** [comment]
@iamxvbaba there are 2 ways you can update the expiration time for the access token.

1. From the dashboard.
<img width="1680" alt="Screenshot 2023-01-30 at 2 10 29 PM" src="https://user-images.githubusercontent.com/6964334/215428194-a5de8660-dfb2-4d07-b906-4da8241a671b.png">
2. Via env variable, set the value for `ACCESS_TOKEN_EXPIRY_TIME` env variable.

Note: Authorizer uses `golang` `time` package to parse the given time. (https://pkg.go.dev/time)
