### ISSUE TITLE
Scopes in /oauth/token endpoint

### ISSUE THREAD

**Issue by felipereyel** [authorizerdev/authorizer#318]
**Version:** 1.1.36

**Describe the bug**

The `scope` field returned in the `/oauth/token` and inside the tokens themselves are of type `List of String`.   
This is an issue because OpenID specifies it to be a space separated list  of values and this breaks some openid client. For example I am having issues with [oidc-client-ts](https://github.com/authts/oidc-client-ts) and though CloudflareAccess connectors.   

Authorizer response:
![image](https://user-images.githubusercontent.com/26462242/216854095-3525b9e5-aeb8-45a9-963d-38e3f2b959fd.png)

Auth0 response for comparison:
![image](https://user-images.githubusercontent.com/26462242/216855410-dfefc351-a9e9-4ec5-a851-cdcffb7af789.png)

**Steps To Reproduce**

This is an demo project that i built that just connects with your openid connect IDP and provides authentication
https://github.com/felipereyel/auth-demo

I connected with my authorizer instance with the `.env` file.   
When you finish login you can see an error (split is not a function) where the lib (oidc-client-ts) expects a space separated list in the scope field but it receives and list already.

![image](https://user-images.githubusercontent.com/26462242/216854471-b1474572-65e7-4f78-8b8b-093923209cf1.png)

**Expected behavior**

Expected the responses (and probably also inside the jwt tokens) to have a space separated list of scopes
![image](https://user-images.githubusercontent.com/26462242/216855457-1cdea0ed-dbb4-441b-84db-8ac499083593.png)

**Additional context**

- OpenID connect specification regarding scopes: https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims

- CloudflareAccess also could not complete the authentication process. I dont know if it is related but just putting here as additional context

This is an app protected by cloudflare to be authenticated by an openid connect IDP
![Kapture 2023-02-05 at 21 18 28](https://user-images.githubusercontent.com/26462242/216854926-24ffa0ae-b62d-4762-bff3-133814e481f5.gif)

This is my configuration on the Authentication part of the settings
![image](https://user-images.githubusercontent.com/26462242/216855230-4decc0b5-0226-48e9-beef-ea8581cca562.png)

**Comment by lakhansamani** [comment]
@felipereyel thank you for sharing the detailed steps to reproduce this issue.
I will work on this issue in this week.

**Comment by lakhansamani** [comment]
@felipereyel in your [example](https://github.com/felipereyel/auth-demo) I made following change for logout to work correctly

<img width="1275" alt="Screenshot 2023-02-08 at 9 40 05 AM" src="https://user-images.githubusercontent.com/6964334/217431331-a315f16f-3d2d-4695-9c9f-d5b989ddc8af.png">
