### ISSUE TITLE
OpenID Connect Test

### ISSUE THREAD

**Issue by felipereyel** [authorizerdev/authorizer#323]
**Version:** 1.1.37

**Describe the bug**

I tested my Authorizer instance against an OpenID Connect test suite: https://openidconnect.net/

It failed on step 3: Verify the user token.
![image](https://user-images.githubusercontent.com/26462242/217436383-49f8ee90-967e-4cd0-b1b6-b96a5e9f7cb6.png)

**Steps To Reproduce**

Fill the test on https://openidconnect.net/

Here is a gif of my test
![Kapture 2023-02-08 at 01 45 18](https://user-images.githubusercontent.com/26462242/217436236-3c34507b-8382-4d50-99e1-6f21a4668a25.gif)

**Expected behavior**

To pass the test.

Example from running the test against a Zitadel instance:
![image](https://user-images.githubusercontent.com/26462242/217438156-bf92b5d9-6c28-4473-93bd-00e8e53b796c.png)

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- Browser chrome

**Additional context**

**Comment by felipereyel** [comment]
PS: I know i leaked my credentials but ill rotate them

**Comment by lakhansamani** [comment]
@felipereyel I tried reproducing it but it worked for me



<img width="907" alt="Screenshot 2023-03-04 at 1 07 20 PM" src="https://user-images.githubusercontent.com/6964334/222882723-0a8cb6c4-8459-41e5-a46f-73b2fc6a9e2e.png">

**Comment by felipereyel** [comment]
I'll try again later today to see if any of the new releases fixed it.
