### ISSUE TITLE
userinfo endpoint should return sub-field, returns id.

### ISSUE THREAD

**Issue by IsmoKarkkainen** [authorizerdev/authorizer#327]
**Version:** 1.1.38

**Describe the bug**

The userinfo endpoint response has a field named "id" and there is no field named "sub". Value of "id" is what is expected to be in "sub" so only the field name is incorrect.

According to https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse : "The sub (subject) Claim MUST always be returned in the UserInfo Response."

**Steps To Reproduce**

Obtain an access token from an Authorizer instance. (Tokens expire and test was done on Authorizer instance that is not publicly accessible, hence no example provided.)

In the following command, replace ADDRESS with proper address and ACCESS_TOKEN with the token (pipe through `jq` is to make the output more readable):
`curl http://ADDRESS/userinfo -H 'authorization: Bearer ACCESS_TOKEN' | jq`

**Expected behavior**

Response JSON object should include "sub" field with value that is now in "id" field.

**Desktop:**

- OS: Linux
- Browser curl
- Version 7.87.0

**Additional context**

The userinfo endpoint was obtained using (substitute proper ADDRESS):
`curl http://ADDRESS/.well-known/openid-configuration | jq`

A sanitized userinfo output looks like this:

```json
{
  "id": "7038f9f6-0268-4a43-8738-978101d9bbc1",
  "email": "test@domain.com",
  "email_verified": true,
  "signup_methods": "basic_auth",
  "given_name": null,
  "family_name": null,
  "middle_name": null,
  "nickname": null,
  "preferred_username": "test@domain.com",
  "gender": null,
  "birthdate": null,
  "phone_number": null,
  "phone_number_verified": false,
  "picture": null,
  "roles": [
    "user"
  ],
  "created_at": 1677074406,
  "updated_at": 1677074406,
  "revoked_timestamp": null,
  "is_multi_factor_auth_enabled": null
}
```

**Comment by lakhansamani** [comment]
@IsmoKarkkainen thank you for reporting this
I will try to resolve this by this week.

**Comment by IsmoKarkkainen** [comment]
Thank you.
