### ISSUE TITLE
Question: How to configure custom claims

### ISSUE THREAD

**Issue by itpropro** [authorizerdev/authorizer#335]
An essential feature for usage in a SaaS or multi-tenant application/environment would be the ability to define custom claims in addition to custom roles. 
Is that currently planned or possible in the admin dashboard, I have not found anything in the documentation or the issues regarding custom claims, for example `organisation_id`, `oragnisation_name`, `licensed_products`, etc..
It would probably be possible with the JWT token script, correct?

**Comment by lakhansamani** [comment]
@itpropro sorry for the late reply.
It is possible to configure JWT claims but right now you cannot add variables other than user_information in custom keys

Example:
<img width="1680" alt="Screenshot 2023-04-01 at 5 38 59 PM" src="https://user-images.githubusercontent.com/6964334/229287763-3743af35-8562-4322-bf4d-d86e42f62a49.png">

Soon will be adding support for async calls + extra_information (user_schema) using which you will be able modify claims in advanced level.

**Comment by Alex-Ferreli** [comment]
I need this feature, there is a release date of it please?

Could be possible to add a "metadata" column to the user entity (that accept a JSON value) and from the actual implementation of Custom Script just work because already have access to it.

**Comment by lakhansamani** [comment]
@Alex-Ferreli which database you need this for?

**Comment by Alex-Ferreli** [comment]
@lakhansamani mainly MSSQL database, but PostgreSQL can be an option too.

**Comment by lakhansamani** [comment]
Okay estimated delivery date for this will be 10th august 

Thanks

**Comment by Alex-Ferreli** [comment]
Fantastic! Thank you!

**Comment by lakhansamani** [comment]
@Alex-Ferreli sorry for the delay added as part of 1.1.63
