### ISSUE TITLE
Configurable default response_type

### ISSUE THREAD

**Issue by feynmanliang** [authorizerdev/authorizer#341]
**Feature Description**

Currently the `response_type` is [defaulted to "token"](https://github.com/authorizerdev/authorizer/blob/77f34e1149b27a735f53894f218b8ff677f7bef4/server/handlers/authorize.go#L94) and this is the parameter that's used in email links. Some libraries like [pow-assent](https://github.com/pow-auth/assent) only support `code` response types, so the current solution is to manually redefine all of these templates.

**Describe the solution you'd like**

A `DEFAULT_RESPONSE_TYPE` environment variable which allows us to override this. We could maintain backwards compatibility by defaulting to "token" when this is missing.

**Describe alternatives you've considered**

**Additional context**

**Comment by lakhansamani** [comment]
@feynmanliang thank you for sharing this,
I will add this env over the weekend 👍

**Comment by lakhansamani** [comment]
@feynmanliang added support for `DEFAULT_AUTHORIZE_RESPONSE_TYPE` and `DEFAULT_AUTHORIZE_RESPONSE_MODE` in #342 will be released as part of `1.1.43`

**Comment by feynmanliang** [comment]
Thank you!! 🥳 🎈
