### ISSUE TITLE
Returning the IDS and Email of the invited users on invitation.

### ISSUE THREAD

**Issue by MussieT** [authorizerdev/authorizer#345]
**Feature Description**

While inviting the members as an admin on `_invite_members`, I wanted to get the ids of the invited users on the response (it can be a list of ids or minimal user information like their email and id of the users who are invited).  I am unsure if this is a needed functionality from your side but was mandatory in my case. I wanted the user id and email for some business logic after they are invited.

I modified the mutation to return what I want on my local setup. Please let me know to submit a PR if this is a valid request.

**Comment by lakhansamani** [comment]
@MussieT thank you for reporting will try to add in upcoming release

**Comment by lakhansamani** [comment]
Released as part of #1.1.46
