### ISSUE TITLE
Don't  Show Client Id

### ISSUE THREAD

**Issue by aixj1984** [authorizerdev/authorizer#357]
**Version:**  0.1.0-local

**Describe the bug**

Don't show client id in Oauth Config Page

**Steps To Reproduce**

Just run by default env file

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by aixj1984** [comment]
![Uploading 微信截图_20230601102722.png…]()

**Comment by aixj1984** [comment]
![微信截图_20230601102722](https://github.com/authorizerdev/authorizer/assets/2499352/66806acd-0a42-4c44-9ae9-3ef75dac4775)

**Comment by aixj1984** [comment]
#140 like  this issue

**Comment by aixj1984** [comment]
![微信截图_20230601105438](https://github.com/authorizerdev/authorizer/assets/2499352/d9efe999-2662-41e3-adb3-306707ab61e0)

**Comment by aixj1984** [comment]
![微信截图_20230601105438](https://github.com/authorizerdev/authorizer/assets/2499352/19137fa8-dd3f-4b71-a1b5-d50399055cda)

**Comment by lakhansamani** [comment]
@aixj1984 this happens when you use authorizer with IP address.
It won't be able to set https cookie in that scenario.

It is recommended to use a domain. But if you want to keep using it with IP address then you will have to set `ADMIN_COOKIE_SECURE=false` env

**Comment by aixj1984** [comment]
Thanks, I get the client id .
