### ISSUE TITLE
Add sms_verification_requests implementation for arangodb provider

### ISSUE THREAD

**Issue by lakhansamani** [authorizerdev/authorizer#361]
**Feature Description**
Implement methods for `sms_verification_requests` collection for arangodb

Ref: https://github.com/authorizerdev/authorizer/blob/main/server/db/providers/sql/sms_verification_requests.go

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MateSousa** [comment]
hey @lakhansamani, can i try?

**Comment by lakhansamani** [comment]
Sure 👍

**Comment by lakhansamani** [comment]
will be resolved in #368
