### ISSUE TITLE
TOTP as MFA

### ISSUE THREAD

**Issue by JokerQyou** [authorizerdev/authorizer#366]
**Feature Description**

Currently the only MFA supported is Email-based OTP. It would be awesome if time-based OTP could be supported. Email sometimes gets delayed, and OTP code is only valid for 1 minute, that could potentially be a problem. TOTP can be managed by most password manager or standalone apps like Google Authenticator.

**Describe the solution you'd like**

Let the user register their own TOTP after login. Basically show an MFA management page after they login, and when registering TOTP, generate a secret and render as QR code, let the user copy the secret or scan the QR code, and have the user input the correct TOTP (a six-digit text) to verify it is correctly saved, and store the secret to database.

Then at each login, if the user has previously registered TOTP, show an input and verify it before returning token.

**Describe alternatives you've considered**

FIDO / WebAuthn might be other MFAs that users can themselves register. For example, one of the supported MFAs is required to finish the login, just like how GitHub let you select one of the MFAs you configured.

**Additional context**

None.

**Comment by lakhansamani** [comment]
Released as part of 1.3.3
