### ISSUE TITLE
Bug: webhook test button calls non-existing graphql command

### ISSUE THREAD

**Issue by c-nv-s** [authorizerdev/authorizer#376]
![authorizer_webhook_testbutton_error](https://github.com/authorizerdev/authorizer/assets/7495833/9be15891-89b1-449d-8d91-96f8116f5d7e)

when clicking the button to test a saved webhook, the graphql query is to 
```
operationName: testEndpoint


query: "mutation  testEndpoint($params: TestEndpointRequest!) {\n  _test_endpoint(params:  $params) {\n    http_status\n    response\n    __typename\n  }\n}"
-- | --
```
from the documentation this query doesn't actually exist and the server always responds with ``422 unprocessable entity``
and the ui show ``endpoint not verified``

**Comment by c-nv-s** [comment]
thanks for fixing.
you might need to double check the webhook triggers.
``user.signup`` webhooks created are not triggering.
whereas ``user.created`` webhooks do work (not sure the difference)

**Comment by lakhansamani** [comment]
@c-nv-s 
`user.created` is triggered when user entry is created in database either via signup process / invite process
`user.signup` is triggered when user email / mobile is verified: https://github.com/authorizerdev/authorizer/blob/e91a81906751713affd0445a60652042bffac703/server/constants/webhook_event.go#L8

**Comment by c-nv-s** [comment]
hey lakhansamani I just wanted to say that although this ticket is fixed, your fix only works when initially creating the webhook for the first time and pressing the button to test the webhook.
That means that once you save the webhook, if you later reopen it from the edit menu and press the button to test the webhook again, it fails to work.
