### ISSUE TITLE
Add *User to ValidateSessionResponse object

### ISSUE THREAD

**Issue by c-nv-s** [authorizerdev/authorizer#379]
**Feature Description**
the recently added ``validate_session`` api https://github.com/authorizerdev/authorizer-go/blob/main/validate_session.go
could be more useful if the response includes a ``*User`` object similar to the way the ``validate_jwt_token`` response includes a ``Claims`` object

**Comment by lakhansamani** [comment]
@c-nv-s thanks will add it in upcoming release 👍

**Comment by c-nv-s** [comment]
@lakhansamani is it still possible to quickly add this for the next release please?

**Comment by lakhansamani** [comment]
@c-nv-s sure, give me weekend time 👍

**Comment by lakhansamani** [comment]
@c-nv-s released as part of 1.1.65
