### ISSUE TITLE
Why does separate endpoints exist for mobile and email login/signup?

### ISSUE THREAD

**Issue by miqe** [authorizerdev/authorizer#381]
**Feature Description**

I don't see the point for mobile and email signup endpoints to exists while using the same input?  Similarly, for the login, except from phone_email/email every other fields are the same.

**Describe the solution you'd like**

I've seen the OTP email/phone verification implementation and its is better to check if phone_number or email is present on the input and proceed to the respective process.

**Additional context**

Should forget_password for mobile be implemented with separate endpoint or different fields but within one input, similar like OTP verification?

**Comment by lakhansamani** [comment]
Agreed we can optimize that @miqe would you like to work on that optimization?
