### ISSUE TITLE
Disable Playground API 

### ISSUE THREAD

**Issue by briannezhad** [authorizerdev/authorizer#385]
**Feature Description**

Be able to Disable Playground API from public access. Anyone can access https://example.com/playground, which may be a channel for mutable security risk.

**Describe the solution you'd like**

- Allow only from certain IP
- Only Accessible to Login Admins
- Disable In General
- Disable for PROD / Allow for DEV

**Describe alternatives you've considered**

None

**Comment by lakhansamani** [comment]
@briannezhad thank you for sharing this, will add feature to disable it in further releases

**Comment by lemonScaletech** [comment]
working on this feature.

**Comment by lakhansamani** [comment]
Resolved in #390
