### ISSUE TITLE
webhook user.created does not fire when email verification is disabled

### ISSUE THREAD

**Issue by c-nv-s** [authorizerdev/authorizer#389]
**Version:** 1.1.65 (currently latest)

**Describe the bug**
``user.created`` webhook is triggered when user entry is created in database either via signup process / invite process
``user.signup`` webhook is triggered when user email / mobile is verified: 

therefore if the DISABLE_EMAIL_VERIFICATION environment variable is set to ``true`` so that email verification is disabled, then a ``user.signup`` webhook should automatically be triggered along with the ``user.created`` webhook.

at the moment this does not happen and only one webhook is triggered/received which is just the ``user.signup`` webhook.
So the ``user.created`` webhook is not additionally detected when it should be.

**Steps To Reproduce**

create webhooks for both ``user.signup`` and ``user.created``
set auth method to username and password
disable email verification
register a new user
observe that only the ``user.signup`` webhook is received

**Expected behavior**
both user.signup webhook and user.created webhook should be triggered

**Comment by scaletech-milan** [comment]
I am working on this feature.
