### ISSUE TITLE
Support macOS arm64 architecture for releases

### ISSUE THREAD

**Issue by VishwasShashidhar** [authorizerdev/authorizer#396]
**Feature Description**

For newer Apple Silicon macs, currently there are no release binaries available. We need to use amd64 builds using Rossetta when trying to run binaries directly.

**Describe the solution you'd like**

Support darwin-arm64 binaries with releases.

**Describe alternatives you've considered**

Running amd64 builds using Rossetta.

**Additional context**

N/A

**Comment by lakhansamani** [comment]
Releasing as part of 1.1.66
