### ISSUE TITLE
Not able to send emails

### ISSUE THREAD

**Issue by tusharmctrl** [authorizerdev/authorizer#404]
According to this article:
https://docs.authorizer.dev/core/email
I have these env variables in my railways deployed instance.
I am using SMTP using Google's APP password. It even says "Password reset link has been sent.

![image](https://github.com/authorizerdev/authorizer/assets/141150938/c99f9c01-ab42-47fa-b63b-ec4372aadb25)

But in reality - when i check the inbox i haven't received any emails. Where am i doing it wrong? Help me out.

- Thanks.

**Comment by lakhansamani** [comment]
@tusharmctrl there would be some error logs in the railway logs section, can you check the logs and see what is failing there?

Also which version of authorizer you are using?

**Comment by tusharmctrl** [comment]
Hi Lakhan. Thanks for your respose. 

Just checked railway logs and everything seems to be right upto the mark. (Every request returned 200 status code)
I am using - 1.1.69 version.

**Comment by lakhansamani** [comment]
Okay I will try to debug this and let you know

**Comment by tusharmctrl** [comment]
![image](https://github.com/authorizerdev/authorizer/assets/141150938/cfd277d7-487f-460b-9243-4ae57581715b)
![image](https://github.com/authorizerdev/authorizer/assets/141150938/a7cc646d-ad07-48b0-beb5-4b76b6526c7f)
![image](https://github.com/authorizerdev/authorizer/assets/141150938/7a1039b8-64ba-4eab-b81a-79f5a1b753f7)


For your context (;

**Comment by yangzhaox** [comment]
Hi @tusharmctrl, how did you solve this issue? I'm using gmail smtp server, and APP password, but could not send out any email. Really appreciate if there is any help. Thanks.

**Comment by lakhansamani** [comment]
@yangzhaox try `LOG_LEVEL=debug` env and you might see the failure reason

**Comment by tusharmctrl** [comment]
Hi @yangzhaox, were you able to figure this out sir?

**Comment by tusharmctrl** [comment]
@yangzhaox Please make sure to add "SMTP Local Name" as "en".
This might be throwing an error "unexpected paremeter" I suppose.

**Comment by yangzhaox** [comment]
@tusharmctrl I leave SMTP local name as "" then it works.

**Comment by lakhansamani** [comment]
JFYI: 

```
// LocalName is the hostname sent to the SMTP server with the HELO command.
// By default, "localhost" is sent.
LocalName string
```
