### ISSUE TITLE
Backend endpoints authentication

### ISSUE THREAD

**Issue by mihaa1** [authorizerdev/authorizer#405]
I have a react+express setup, deployed on railway.
I also have a deployed authorizer instance on railway (separate).

I got the frontend working - out of the box login/signup page etc.
I'm missing how am I supposed to protect the backend endpoints?
Is there additional setup to be done?
Couldn't find anything in the docs/youtube

**Comment by lakhansamani** [comment]
@mihaa1 here is one
https://blog.authorizer.dev/authorize-nodejs-apis-using-authorizer

**Comment by mihaa1** [comment]
@lakhansamani for backend implementation (node/express)
What should the redirectURL be in the Authorizer config?
It says FRONTEND_URL - what is the purpose of this on the backend?
