### ISSUE TITLE
Email Sending on SignUp not working

### ISSUE THREAD

**Issue by shiftlabs1** [authorizerdev/authorizer#412]
**Version:** 1.2.0

**Describe the bug**
I have used two mail services (Mailjet and MailerSend), Tried all Possible ports and in both cases Mails are not getting delivered after signup . The services also show no mail Sent (meaning their end points were never Called). Also Railway logs for Authorizerdev instance shows no errors during this sign Up call. See screenshot below . I have been able to send mails from my front end to MailerSend . I had to do that before posting this issue 

**Steps To Reproduce**

**Expected behavior**
Should Send the signup or any other mail after successful action 

**Screenshots**
<img width="990" alt="Screenshot 2023-10-29 at 10 02 03 AM" src="https://github.com/authorizerdev/authorizer/assets/104312183/45c8307a-48a9-4270-868f-3f3942b1b292">

**Desktop (please complete the following information):**
Railway cloud platform 
**Additional context**

**Comment by lakhansamani** [comment]
@shiftlabs1 how did you resolve it?

**Comment by shiftlabs1** [comment]
I just switched to another provider that worked. I think they had internal restrictions i am not aware of
