### ISSUE TITLE
"Forget password" is shown when magic link is on but basic auth is off

### ISSUE THREAD

**Issue by yangzhaox** [authorizerdev/authorizer#427]
**Version:** 1.2.4

**Describe the bug**

"Forget password" is not needed if basic auth (user/pwd) is off but it is still displayed.

**Steps To Reproduce**

1. configure authorizer to use magic link but not basic auth
1. open https://auth.moochee.us/app in Chrome

**Expected behavior**

"forget password" should not be shown

**Screenshots**

<img width="387" alt="Screenshot 2023-12-02 at 9 48 35 AM" src="https://github.com/authorizerdev/authorizer/assets/722332/f4aa4537-40be-4449-8fa7-bb2e6266a4f1">
<img width="473" alt="Screenshot 2023-12-02 at 9 47 30 AM" src="https://github.com/authorizerdev/authorizer/assets/722332/7212dcce-3da2-4169-be80-bf29353eb59b">

**Desktop (please complete the following information):**

- OS: MacOS latest
- Browser Chrome latest
- Version 119.0.6045.105

**Comment by yangzhaox** [comment]
Hi @lakhansamani this problem still exists after upgrading to the latest 1.3.3.

**Comment by lakhansamani** [comment]
@yangzhaox released as part of 1.3.4
