### ISSUE TITLE
UI elements not responsive on mobile

### ISSUE THREAD

**Issue by yangzhaox** [authorizerdev/authorizer#428]
**Version:** 1.2.4

**Describe the bug**

Some UI elements are not responsive on mobile, see attached screeshot.

**Steps To Reproduce**

1. open https://auth.moochee.us/app in Chrome
2. open developer tools with option + command + I
3. toggle to mobile mode e.g. iPhone 12 Pro

**Expected behavior**

All UI elements should be responsive on mobile

**Screenshots**

<img width="419" alt="Screenshot 2023-12-02 at 10 57 34 AM" src="https://github.com/authorizerdev/authorizer/assets/722332/fed90e72-cad6-4a98-b709-3be3d2e7bcc9">

**Desktop (please complete the following information):**

- OS: MacOS latest
- Browser Chrome latest
- Version 119.0.6045.105

**Comment by lakhansamani** [comment]
@yangzhaox thank you for reporting fixing it with the upcoming release
