### ISSUE TITLE
RESET_PASSWORD_URL default not working and override also

### ISSUE THREAD

**Issue by mihaa1** [authorizerdev/authorizer#434]
Reset password email - link to the reset password is 
```
app.url/?token=123
```
and not 
```
app.url/reset-password/?token=123
```
I tried setting the env var also and that didn't work.

**Comment by mihaa1** [comment]
I tried using local instance and prod on railway.
Iniitally /reset-password was good for me - I create a page with this path in my app, without setting the RESET_PASSWORD_URL env var.

But I saw the link from the email points to app.url?token=123 and not app.url/reset-password/?token=123
Then I tried setting it in the .env in the local instance and in env vars in railway on production instance.
Both didn't work.

I'm trying to understand whether I'm missing something and this env var is not supposed to do what I think.

**Comment by lakhansamani** [comment]
@mihaa1 so this is how the reset password URL is decided

priority 1: if `redirect_uri` passed as param to `forgot_password`
priority 2: if `RESET_PASSWORD_URL` is set in env (Note: this should be full URL `https://some_frontend_app.url/...`
priority 3: if none of the above is set we use the default app `reset-password` `/app/reset-password` prefixed with your authorizer instance URL

**Comment by mihaa1** [comment]
1) where does ```redirect_uri``` passed? Im using the react sdk and the full <Authorizer/> component. The component controls the forgot passowrd
2) setting ```RESET_PASSWORD_URL=http://localhost:5173/login``` is not working. The email is sent with the link http://localhost:5173?token=123

**Comment by mihaa1** [comment]
>  I suppose you are using `Authorizer` component right?

YES!
thank u!

**Comment by lakhansamani** [comment]
@mihaa1 after digging more into the code, I found a possibility where you can do this
Just add `redirect_uri` in your URL when rendering `<Authorizer>` component

example `https://localhost:8080/forgot-password?redirect_uri='https://abc.com/reset-password'`
