### ISSUE TITLE
Error logging in with incorrect password

### ISSUE THREAD

**Issue by rudemex** [authorizerdev/authorizer#458]
**Version:** 1.4.3

**Describe the bug**

I have Authorizer configured to register user and require email validation, after registering I try to log in with a wrong password, it logs in anyway returning the message “Please check email inbox for the OTP”.

**Steps To Reproduce**

1- Have Authorizer configured to register user and require email validation.
2- Register a user in http://localhost/app/signup and do not validate by email.
3- Login to http://localhost/app using the previously registered email, but using a wrong password.

**Expected behavior**

You should not log in, even if the email is not verified, you should validate if the password is correct or not, if it is correct, return the message to validate the email, and if it is incorrect, notify that the data is not correct.

**Screenshots**

![image](https://github.com/user-attachments/assets/9625dcaf-2468-4e6a-a56e-963fee75c0a4)

**Desktop (please complete the following information):**

- OS: MacOS. Sonoma 14.5
- Browser Chrome
- Version 126.0.6478.183

**Additional context**

**Comment by lakhansamani** [comment]
@rudemex thank you for reporting it. I will look into it

**Comment by lakhansamani** [comment]
@rudemex curious to know if you configured smtp server or not? If not email validation does not work

**Comment by rudemex** [comment]
hi @lakhansamani , yes, do the smtp configuration with resend, but never verify the email, as there may be a case that the account is never verified via email.

**Comment by lakhansamani** [comment]
Thank you for sharing I will look into this issue

**Comment by lakhansamani** [comment]
I was able to debug this.
It is more of a UI bug. I am fixing it

**Comment by lakhansamani** [comment]
@rudemex resolved in 1.4.4
