### ISSUE TITLE
Reset Password email button isn't working.

### ISSUE THREAD

**Issue by agarwal-nitesh** [authorizerdev/authorizer#79]
**Version:** 0.4

**Describe the bug**

Verify email / Reset password email template HTML is being sent as escaped text.

**Steps To Reproduce**

Click on Forgot Password.

**Expected behaviour**

The HTML email template should be sent with a right hyperlinked button. Something like the following may be used: https://github.com/agarwal-nitesh/authorizer/commit/3b881776b54328c7dacfcbc9ca4f5dd2c71d929b

**Comment by lakhansamani** [comment]
@agarwal-nitesh thanks for reporting it.

This is how the email looked alike and I was able to click "Confirm Button"

<img width="1440" alt="Screenshot 2021-12-15 at 3 41 54 AM" src="https://user-images.githubusercontent.com/6964334/146087534-a4a241b0-6901-435e-a5ae-cc854ac83a33.png">

Though, if your changes fixes any specific html issues, please raise a PR and I can merge it.

Also this change is not relevant as "/app" is builtin app url which user can use incase if they don't want to built UI, where as `APP_URL` constant/env is set based on the frontend origin requests, so it may or may not have `build/` path.

https://github.com/agarwal-nitesh/authorizer/commit/3b881776b54328c7dacfcbc9ca4f5dd2c71d929b#diff-5efd4fd9208dae00a924b10a8f6f9807c78e5522dbe087646a42ef726c493f5eR76

**Comment by agarwal-nitesh** [comment]
I see. I might have messed up while setting up probably. This is what I was getting. Closing the bug.


![Screenshot 2021-12-15 at 10 42 01 AM](https://user-images.githubusercontent.com/37532307/146127368-3fcbde46-4798-4471-a626-6004f85ce77a.png)
.

**Comment by lakhansamani** [comment]
@agarwal-nitesh  In current versions we don't support updating email templates. But in future that will possible via dashboard. Keep that in mind if go-mail is better library I am open to merge your PR 👍

**Comment by agarwal-nitesh** [comment]
I am not sure about that. I am using go-mail to avoid SSL in the local setup. But the template is definitely a better option than string formatting.

**Comment by lakhansamani** [comment]
@agarwal-nitesh I agree. In that case please raise the PR for the changes you have made. I will merge it.

**Comment by agarwal-nitesh** [comment]
@lakhansamani The commit above wasn't meant to be a PR :). I will make the template changes and create a PR. I am a little bit occupied, I will do it by early next week.
