### ISSUE TITLE
Add ability to manage email templates

### ISSUE THREAD

**Issue by dselman** [authorizerdev/authorizer#97]
**Feature Description**

Ability to configure templates used for sent emails.

**Describe the solution you'd like**

Control of colors, text, fonts, logos etc to conform to brand style, including the ability to merge in data from the user profile.

**Describe alternatives you've considered**

One approach would be to support Sendgrid Dynamic Transactional Templates, allowing the admin to configure the IDs of a Sendgrid templates to use for the emails sent and then passing the Authenticator `user` data to Sendgrid — allowing the admin to use the graphical Sendgrid template designer to define their templates and to build dynamic content based on the data passed from Authenticator.

https://docs.sendgrid.com/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates

**Additional context**

**Comment by lakhansamani** [comment]
Thanks @dselman for reporting this.
Will add to the roadmap and take up next once done with #90

**Comment by hmmhmmhm** [comment]
I hope this function will be supported simply by replacing HTML.

**Comment by lakhansamani** [comment]
@hmmhmmhm yes this will be html template that one will be able to create using [wyswig](https://github.com/facebook/draft-js) editor
